server.port=8080
spring.application.name=SchoolSystem


spring.profiles.active=sqlserver


spring.thymeleaf.cache=false
spring.thymeleaf.encoding=UTF-8


spring.jackson.serialization.indent-output=true
spring.jackson.time-zone=UTC


server.servlet.session.timeout=30m
server.servlet.session.cookie.name=JSESSIONID
server.servlet.session.cookie.http-only=true
server.servlet.session.cookie.secure=false

logging.level.root=INFO
logging.level.com.assel=DEBUG
logging.level.org.springframework.security=WARN

spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=${MAIL_USERNAME:meiremkhanasel@gmail.com}
spring.mail.password=${MAIL_PASSWORD:bzbbfmuqxmrhzyxn}
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true
spring.mail.properties.mail.smtp.starttls.required=true
spring.mail.properties.mail.smtp.connectiontimeout=5000
spring.mail.properties.mail.smtp.timeout=5000
spring.mail.properties.mail.smtp.writetimeout=5000
spring.mail.properties.mail.smtp.ssl.trust=smtp.gmail.com
spring.mail.properties.mail.debug=true
spring.jpa.hibernate.ddl-auto=update

spring.h2.console.path=/h2-console
spring.h2.console.settings.web-allow-others=false


server.servlet.encoding.charset=UTF-8
server.servlet.encoding.enabled=true
server.servlet.encoding.force=true
server.tomcat.uri-encoding=UTF-8
