spring.datasource.url=jdbc:sqlserver://localhost:1433;databaseName=SchoolDB;integratedSecurity=false;encrypt=false;trustServerCertificate=true
spring.datasource.driver-class-name=com.microsoft.sqlserver.jdbc.SQLServerDriver
spring.datasource.username=sa
spring.datasource.password=sa


spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.open-in-view=true
spring.jpa.properties.hibernate.hbm2ddl.halt_on_error=false

spring.h2.console.enabled=false
